config/routes.rb
Regionsps::Application.routes.draw do

  resources :events, :only => [:index]
  resources :articles, :only => [:index], :path => 'articulos'
  put 'admin/articulos/:id/active', to: 'admin/articles#active', :as => "admin_active_article"
  put 'admin/articulos/:id/publish', to: 'admin/articles#publish', :as => "admin_publish_article"

  resources :sessions, :only => [:new, :create, :destroy]
  get 'forgot_password'           => 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password_request', :as => "reset_password_request"
  get 'reset_password', to: 'sessions#reset_password', :as => "reset_password"
  post 'update_password', to: 'sessions#update_password', :as => "update_password"
  
  match '/recursos'              => 'resources#categories'
  match '/recursos/:id'          => 'resources#index', :as => :recursos_f
  match '/recursos/:c_id/:t_id'  => 'resources#bytag', :as => :recursos_t
  match '/nosotros'              => 'static_pages#about_us'
  match '/admin'                 => 'sessions#admin'
  match '/signin'                => 'sessions#create', :via => :post
  match '/signin'                => 'sessions#admin', :via => :get
  match '/signout'               => 'sessions#destroy'
  match '/calendar'              => 'events#index'
  match '/dashboard'             => 'admin/stadistics#index'
  match '/contact_us'            => 'contacts#new', :via => :get, :as => 'contacts'
  match '/contact_us'            => 'contacts#send_message'
  match '/message_sent'          => 'contacts#sent'
  match '/trips'            => 'events#trips', :via => :get, :as => 'trips'

  namespace :admin do
    resources :stadistics
    resources :articles, :path => 'articulos'
    resources :goals
    resources :resources, :path => 'recursos' do
      resources :tags, :controller => "tags"
    end

    get '/goals/:year/:chapel' => 'goals#sendToStake', as: 'sendToStake'
    match '/goals/:year/:user/:chapel' => 'goals#index', as: 'goals_index'

    match '/dashboard'           => 'stadistics#index'
    match 'recursos/new_tag/:id' => 'resources#new_tag', :as => :new_tag, :via => :post
    match 'recursos/add_tag/:id' => 'resources#add_tag', :as => :add_tag, :via => :post
    
    get '/stadistic/:month/:year/:chapel/:stake/:user'  => 'stadistics#month', :as => :stadistic_m
    
    get '/stadistic/:chapel/:stake/:user/:year' => 'stadistics#lastyears', as: 'lastyears'
    get '/stadistic/export' => 'stadistic#export', as: 'export'

    resources :events
    match 'events/:id/' => 'events#invite', :as => :invite, :via => :post
    match 'events/:event_id/:group_id' => 'events#uninvite', :as => :uninvite, :via => :delete
    

    resources :users, :path => 'usuarios' do
      resources :roles, :except => [:index, :show]
      resources :groups, :path => 'grupos', :only => [:new, :create, :destroy]
    end    
    
    resources :roles, :only => [:index]
    resources :stories, :path => 'historias', :controller => "stories", :except => [:edit, :update]
    
    resources :categories, :path => 'categorias'
    match 'categorias/:id/' => 'categories#add_tag', :as => :add_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#remove_tag', :as => :remove_tag, :via => :delete
    match 'categorias/:category_id/:tag_id' => 'categories#down_tag', :as =>:down_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#up_tag', :as =>:up_tag, :via => :put
  end


  #match '/articulos/articulo1' => 'static_pages#articulo1', :as => :articulo1
  #match '/articulos/articulo2' => 'static_pages#articulo2', :as => :articulo2
  #match '/articulos/articulo3' => 'static_pages#articulo3', :as => :articulo3
  #match '/articulos/articulo4' => 'static_pages#articulo4', :as => :articulo4
  # match '/articulos/articulo5' => 'static_pages#articulo5', :as => :articulo5

  match '/admin/roles/new' => 'admin/roles#new_empty', :via => :get
  match '/admin/roles/new' => 'admin/roles#create_empty', :via => :post
  match '/admin/roles/:name' => 'admin/roles#show', :via => [:post, :get], :as => :admin_role_show
  match '/admin/roles/:name' => 'admin/roles#destroy', :via => :delete, :as => '/admin/roles/update'
  match '/admin/roles/:name/permissions' => 'admin/permissions#add_permissions',:via => :post,
   :as => :admin_role_permissions

  root :to => 'home#index'

  match '/access_denied' => 'static_pages#access_denied', :as => :access_denied
  match '/*rest' => 'static_pages#error_page', :as => :error_page



end

app/models/article.rb
class Article < ActiveRecord::Base
  has_one :resource,:foreign_key => "article_id", :dependent => :destroy
  attr_accessible :active, :published, :resource_attributes

  accepts_nested_attributes_for :resource,
                                :reject_if => :all_blank,
                                :allow_destroy => true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  def index
    if puede "Ver Articulo"
      if params[:page].nil?
        params[:page] = 1
      end
      @articles = Article.order("id desc").paginate(:page => params[:page], :per_page => 15)
    else
      redirect_to access_denied_path
    end
  end

  def active
    if puede "Modificar Articulo"
      @article = Article.find(params[:id])

      @article.active = !@article.active

      respond_to do |format|
      if @article.save
          flash[:notice] = "El articulo #{@article.active ? ' se mostrara' : 'no se mostrara'} en el slider principal."
      else
          flash[:alert] = "Lo sentimos, El articulo no pudo #{!@article.active ? 'mostrar en' : 'quitar de'} el slider."
      end
        format.js
      end
    else
      redirect_to access_denied_path
    end
  end

  def publish
    if puede "Modificar Articulo"
      @article = Article.find(params[:id])

      @article.published = !@article.published

      respond_to do |format|
        if @article.save
          flash[:notice] = "El articulo fue marcado como #{@article.published ? 'publicado' : ' no publicado'}."
        else
          flash[:alert] = "Lo sentimos, El articulo no pudo ser marcado como #{!@article.published ? 'publicado' : 'no publicado'}."
        end
        format.js
      end
    else
      redirect_to access_denied_path
    end
  end

  def new
    if puede "Crear Articulo"
      @article = Article.new
      @article.resource= Resource.new
    else
      redirect_to access_denied_path
    end
  end

  def create
    if params[:cancel]
      redirect_to admin_articles_url
    else
      @article = Article.new(params[:article])
      if !params[:article][:resource_attributes][:file].nil?
        @article.resource.content_type = params[:article][:resource_attributes][:file].content_type
      end
      if @article.save!
        t = Tag.find_by_title("GENERAL")
        if t.nil?
          t = Tag.create(:title => "GENERAL")
        end
        tt = Tagging.new
        tt.resource_id = @article.resource.id
        tt.tag_id = t.id
        tt.save

        redirect_to admin_article_path(@article)
        return
      else
        render :action => "new"
      end
    end
  end

  def show
    if puede "Ver Articulo"
      @resource = Resource.find(params[:id])
      @tags_available = Array.new
      @tags = Array.new
      tmp = [-1]

      tags = Tagging.where(:resource_id => @resource.id)
      tags.each do |t|
        tmp.push(t.tag_id)
      end
      #@tags = Tag.where('id in (?)', tmp)

      tags = Tag.where('id not in (?)', tmp)
      tags.each do |t|
        @tags_available.push([t.title, t.id])
      end
    else
      redirect_to access_denied_path
    end
  end

  def edit
    if puede "Modificar Articulo"
      @article = Article.find(params[:id])
    else
      redirect_to access_denied_path
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:resource])
      redirect_to admin_articles_path
    else
      render "edit"
    end
  end

  def destroy
    if puede "Eliminar Articulo"
      @article = Article.find(params[:id])

      respond_to do |format|
        if @article.destroy
          flash[:notice] = "El articulo fue eliminado."
        else
          flash[:alert] = "Lo sentimos, El articulo no pudo ser eliminado."
        end
        format.js
      end
    else
      redirect_to access_denied_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "application"
  def index
    if params[:page].nil?
      params[:page] = 1
    end
    @articles = Article.where(:published=>true).order("id desc").paginate(:page => params[:page], :per_page => 15)
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<div id="article_<%= article.id %>" class="row article-archive">
  <div class="span12">
    <div class="span3">
      <a href="<%= article.resource.file %>" target="_blank">
        <img src="<%= article.resource.thumbnail %>">
      </a>
    </div>
    <div class="span8 admin-articles-text-align">
      <%= article.resource.description %><br/> <a class="articulo" style="text-width: bold" href="<%= article.resource.file %>" target="_blank"> [Ver Articulo]</a>
    </div>
  </div>
  <div class="span12">

    <%= link_to "Elminar", admin_article_path(article), remote: true, method: :delete, data: { confirm: "Estas seguro de querer eliminar el articulo?" } %>
    - <%= link_to "#{article.published ? 'Quitar Publicación' : 'Publicar'}", admin_publish_article_path(article),class: "publish_#{article.id}", remote: true, method: :put %>
    - <%= link_to "#{article.active ? 'No Mostrar' : 'Mostrar'}", admin_active_article_path(article),class: "active_#{article.id}", remote: true, method: :put %>
    - <%= link_to "Modificar", edit_admin_article_path(article) %>
  </div>
</div>

app/views/admin/articles/_edit_resource_fields.html.erb
<div class"name">
<%= f.label :url, 'o URL', :class => 'nameLabel' %>
<%= f.text_field :url, :placeholder => 'URL de recurso existente...' %>
</div>
<div class="name">
  <%= f.label :description, 'Descripción', :class => 'nameLabel' %>
  <%= f.text_area :description, :placeholder => 'Descripción del recurso...' %>
</div>

app/views/admin/articles/_resource_fields.html.erb
<div class="name">
  <%= f.label :filename, 'Título', :class => 'nameLabel' %>
  <%= f.text_field :filename, :placeholder => 'Título...' %>
</div>
<div class"name">
<label>Archivo*</label>
<div class="FileUpload" id="FileUpload">
  <input type="file" size="24" class="BrowserHidden" id="BrowserHidden" onchange="getElementById('FileField').value = getElementById('BrowserHidden').value;" name="article[resource_attributes][file]"/>
  <div class="BrowserVisible" id="BrowserVisible">
    <input type="text" class="FileField" id="FileField" />
  </div>
</div>
</div>
<div class"name">
<%= f.label :url, 'o URL', :class => 'nameLabel' %>
<%= f.text_field :url, :placeholder => 'URL de recurso existente...' %>
</div>
<div class="name">
  <%= f.label :description, 'Descripción', :class => 'nameLabel' %>
  <%= f.text_area :description, :placeholder => 'Descripción del recurso...' %>
</div>
<div class"name">
<label>Vista previa* (Tamaño de imagen recomendada: 960 x 396 ) </label>
<div class="FileUpload" id="FileUpload2">
  <input type="file" size="24" class="BrowserHidden" id="BrowserHidden2" onchange="getElementById('FileField2').value = getElementById('BrowserHidden2').value;" name="article[resource_attributes][thumbnail]"/>
  <div class="BrowserVisible">
    <input type="text" class="FileField" id="FileField2"/>
  </div>
</div>
</div>
<br/><br/>

app/views/admin/articles/active.js.erb
$("#notice").html("<%= escape_javascript( render 'shared/message').html_safe %>");
$(".active_<%= @article.id %>").text("<%= @article.active ? "No Mostrar" : "Mostrar" %>");

app/views/admin/articles/destroy.js.erb
$("#notice").html("<%= escape_javascript( render 'shared/message').html_safe %>");
$("#article_<%= @article.id %>").fadeOut();

app/views/admin/articles/edit.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-form span3"></div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Editar articulo</h2>
            <%= form_for [:admin, @article], :html => {:multipart => true} do |f| %>

              <div class="name">
                <%= f.label :published, 'Publicar?', :class => 'nameLabel' %>
                <%= f.check_box :published %>
              </div>
              <div class="name">
                <%= f.label :active, 'Mostrar? (Si lo marca sera mostrado en el slider principal)', :class => 'nameLabel' %>
                <%= f.check_box :active %>
              </div>

              <%= f.fields_for :resource do |r| %>
                  <%= render "edit_resource_fields", :f => r %>
              <% end %>
                
              <button type="submit" name="create">Actualizar articulo</button>
            <% end %>
        </div>
    </div>
</div>

<div class="call-to-action-text ">
    <div class="ca-button">
        <a href="<%= admin_articles_path %>">Atrás</a>
    </div>
</div>

app/views/admin/articles/index.html.erb
<div class="page-title">
  <div class="container">
    <div class="row">
      <div class="span12">
        <i class="icon-folder-open page-title-icon"></i>
        <h2>Articulos</h2>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <%= render partial: 'article', collection: @articles %>

  <%= will_paginate @articles %>
</div>


<div class="call-to-action-text ">

  <% if puede "Crear Articulo" %>
      <div class="ca-button">
        <a href="<%= new_admin_article_path %>">Nuevo articulo</a>
      </div>
  <% end %>
</div>

app/views/admin/articles/new.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-form span3"></div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Nuevo Articulo</h2>
            <%= form_for [:admin, @article], :html => {:multipart => true} do |f| %>

              <div class="name">
                <%= f.label :published, 'Publicar', :class => 'nameLabel' %>
                <%= f.check_box :published %>
              </div>
              <div class="name">
                <%= f.label :active, 'Activo (Si lo marca sera mostrado en el slider principal)', :class => 'nameLabel' %>
                <%= f.check_box :active, :placeholder => 'Si no se especifica se usará un número auto incremental...' %>
              </div>

              <%= f.fields_for :resource do |r| %>
                  <%= render "resource_fields", :f => r %>
              <% end %>
                
              <button type="submit" name="create">Subir articulo</button>
            <% end %>
        </div>
    </div>
</div>

<div class="call-to-action-text ">
    <div class="ca-button">
        <a href="<%= admin_articles_path %>">Atrás</a>
    </div>
</div>

app/views/admin/articles/publish.js.erb
$("#notice").html("<%= escape_javascript( render 'shared/message').html_safe %>");
$(".publish_<%= @article.id %>").text("<%= @article.published ? "Quitar Publicación" : "Publicar" %>");

app/views/admin/articles/show.html.erb
<script type="text/javascript">
var var_control = 1, nuevo = 0;
function show_new_tag(){ 
	$('input[type="hidden"]').filter("[name='new_tag']").each (function() {  this.value = '' });
	$('div[id="taggear_div"]').each (function() {  this.style['display'] = 'none' });
	$('a[id="edit_a"]').each (function() {  this.style['display'] = 'none' });
	$('div[id="new_tag_div"]').each (function() {  this.style['display'] = 'block' });
	nuevo = 1;
}
function hide_new_tag(){ 
	$('div[id="new_tag_div"]').each (function() {  this.style['display'] = 'none' });
	$('div[id="taggear_div"]').each (function() {  this.style['display'] = 'block' });
	$('input[type="text"]').filter("[name='new_tag']").each (function() {  this.value = '' });
	$('a[id="edit_a"]').each (function() {  this.style['display'] = 'inline' });	
	nuevo = 0;
}
function display_edit(){ 
	if (var_control == 1 && nuevo == 0){
		$('div[id="edit_tag_div"]').each (function() {  this.style['display'] = 'block' });
		$('div[id="taggear_div"]').each (function() {  this.style['display'] = 'none' });
		var_control = 2;
	}else{
		$('div[id="edit_tag_div"]').each (function() {  this.style['display'] = 'none' });
		$('div[id="taggear_div"]').each (function() {  this.style['display'] = 'block' });
		var_control = 1;
	}
}
</script>

<div class="page-title">
    <div class="row">
    	<div class="contact-form span3"></div>        
        <div class=" contact-us contact-form login-form span7">	
			<h3 style="margin: auto; padding-left: 3%">
				<%= @resource.filename%>
			</h3>
			<p>Descripción: <%= @resource.description%></p>
			<% if @resource.tags.any? %>
			<table id="hor-minimalist-b">
				<thead>
					<tr>
						<th scope="col">Tópicos</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
				<% @resource.tags.each do |u| %>
					<tr>
						<td><%= u.title %></td>
						<td>
							<% if puede("Eliminar Tag") %>
							<%= link_to (image_tag('file_delete.png', :size =>'15x15')), admin_resource_tag_path(@resource, u), :method => :delete, :data => { :confirm => '¿Esta seguro?' }%>
							<% end %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
			<% end %>
			<hr>
			<%= form_tag({:action => 'add_tag', :controller => 'admin/resources'}) do |f| %>
				<div class="name">
					<%= label_tag :tag_id, "Tópico" %>
					<%= select_tag :tag_id, options_for_select(@tags_available.push(["Nuevo tópico", -1])),
					{:onChange => "if(this.value == -1) show_new_tag();else hide_new_tag();"} %>
					<% if puede("Modificar Tag") %>
					<a style="display: <% if @tags_available.size > 1 %>inline<% else %>none<% end %> " id="edit_a" href="" onclick="display_edit();return false;">
						<%= image_tag('file_edit.png', :size => '25x25', :style => 'vertical-align: top;') %> 
					</a>
					<% end %>
					<br/>
					<div id="edit_tag_div" style="display:none">
						<input id="edit_tag" type="text" placeholder="Cambiar tópico por..." name="edit_tag"></input>
						<button id="edit_btn" type="submit" name="edit">Cambiar tópico</button>
					</div>				
					<div id="taggear_div" style="display:<% if @tags_available.size > 1 %>block<% else %>none<% end %>">
						<button type="submit" name="create">Agregar tópico</button>
					</div>
				</div>
			<% end %>
			<div id="new_tag_div" style="display: <% if @tags_available.size > 1 %>none<% else %>block<% end %>">
				<%= form_tag({:action => 'new_tag', :controller => 'admin/resources'}) do |f|%>
					<input id="new_tag" type="text" placeholder="Nuevo tópico" name="new_tag"></input>
					<button type="submit" name="create">Crear tópico</button>
				<% end %>
			</div>
			<br/>
		</div>
	</div>
</div>
<div class="call-to-action-text ">
	<div class="ca-button">
	    <a href="<%= admin_resources_path %>">Atrás</a>
	</div>
	<% if puede "Ver Recurso" %>
	<div class="ca-button">
	    <a href="<%= @resource.file_url %>" target="_blank">Descargar recurso</a>
	</div>
	<% end %>
	<% if puede "Modificar Recurso" %>
	<div class="ca-button">
	    <a href="<%= edit_admin_resource_path(@resource) %>" target="_blank">Modificar recurso</a>
	</div>
	<% end %>
</div>