config/routes.rb
Regionsps::Application.routes.draw do

  resources :events, :only => [:index]
  resources :articles, :only => [:index], :path => 'articulos'
  put 'admin/articulos/:id/active', to: 'admin/articles#active', :as => "admin_active_article"
  put 'admin/articulos/:id/publish', to: 'admin/articles#publish', :as => "admin_publish_article"

  resources :sessions, :only => [:new, :create, :destroy]
  get 'forgot_password'           => 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password_request', :as => "reset_password_request"
  get 'reset_password', to: 'sessions#reset_password', :as => "reset_password"
  post 'update_password', to: 'sessions#update_password', :as => "update_password"
  
  match '/recursos'              => 'resources#categories'
  match '/recursos/:id'          => 'resources#index', :as => :recursos_f
  match '/recursos/:c_id/:t_id'  => 'resources#bytag', :as => :recursos_t
  match '/nosotros'              => 'static_pages#about_us'
  match '/admin'                 => 'sessions#admin'
  match '/signin'                => 'sessions#create', :via => :post
  match '/signin'                => 'sessions#admin', :via => :get
  match '/signout'               => 'sessions#destroy'
  match '/calendar'              => 'events#index'
  match '/dashboard'             => 'admin/stadistics#index'
  match '/contact_us'            => 'contacts#new', :via => :get, :as => 'contacts'
  match '/contact_us'            => 'contacts#send_message'
  match '/message_sent'          => 'contacts#sent'
  match '/trips'            => 'events#trips', :via => :get, :as => 'trips'

  namespace :admin do
    resources :stadistics
    resources :articles, :path => 'articulos'
    resources :goals
    resources :resources, :path => 'recursos' do
      resources :tags, :controller => "tags"
    end

    get '/goals/:year/:chapel' => 'goals#sendToStake', as: 'sendToStake'
    match '/goals/:year/:user/:chapel' => 'goals#index', as: 'goals_index'

    match '/dashboard'           => 'stadistics#index'
    match 'recursos/new_tag/:id' => 'resources#new_tag', :as => :new_tag, :via => :post
    match 'recursos/add_tag/:id' => 'resources#add_tag', :as => :add_tag, :via => :post
    
    get '/stadistic/:month/:year/:chapel/:stake/:user'  => 'stadistics#month', :as => :stadistic_m
    
    get '/stadistic/:chapel/:stake/:user/:year' => 'stadistics#lastyears', as: 'lastyears'
    get '/stadistic/export' => 'stadistic#export', as: 'export'

    resources :events
    match 'events/:id/' => 'events#invite', :as => :invite, :via => :post
    match 'events/:event_id/:group_id' => 'events#uninvite', :as => :uninvite, :via => :delete
    

    resources :users, :path => 'usuarios' do
      resources :roles, :except => [:index, :show]
      resources :groups, :path => 'grupos', :only => [:new, :create, :destroy]
    end    
    
    resources :roles, :only => [:index]
    resources :stories, :path => 'historias', :controller => "stories", :except => [:edit, :update]
    
    resources :categories, :path => 'categorias'
    match 'categorias/:id/' => 'categories#add_tag', :as => :add_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#remove_tag', :as => :remove_tag, :via => :delete
    match 'categorias/:category_id/:tag_id' => 'categories#down_tag', :as =>:down_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#up_tag', :as =>:up_tag, :via => :put
  end


  #match '/articulos/articulo1' => 'static_pages#articulo1', :as => :articulo1
  #match '/articulos/articulo2' => 'static_pages#articulo2', :as => :articulo2
  #match '/articulos/articulo3' => 'static_pages#articulo3', :as => :articulo3
  #match '/articulos/articulo4' => 'static_pages#articulo4', :as => :articulo4
  # match '/articulos/articulo5' => 'static_pages#articulo5', :as => :articulo5

  match '/admin/roles/new' => 'admin/roles#new_empty', :via => :get
  match '/admin/roles/new' => 'admin/roles#create_empty', :via => :post
  match '/admin/roles/:name' => 'admin/roles#show', :via => [:post, :get], :as => :admin_role_show
  match '/admin/roles/:name' => 'admin/roles#destroy', :via => :delete, :as => '/admin/roles/update'
  match '/admin/roles/:name/permissions' => 'admin/permissions#add_permissions',:via => :post,
   :as => :admin_role_permissions

  root :to => 'home#index'

  match '/access_denied' => 'static_pages#access_denied', :as => :access_denied
  match '/*rest' => 'static_pages#error_page', :as => :error_page



end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessor :name_select, :permissions_list
  attr_accessible :name, :description, :name_select, :permissions

  has_and_belongs_to_many :permissions
  has_and_belongs_to_many :users, :join_table => "users_roles"

  before_save :right_name
  after_save  :update_permissions

  private
  	def right_name
  		if self.name_select.present? and self.name_select != "Nuevo rol"
  			self.name = self.name_select
  		end
  	end

    def update_permissions
      if permissions_list.present?
        permissions.delete_all
        selected_pers = permissions_list.nil? ? []: permissions_list.collect{|id,other| Permission.find(id)}
        selected_pers.each {|per| self.permissions << per}
      end
    end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < AdminController
	def index	
		if puede "Ver Rol"
			@roles = Role.select("distinct name, description")
		else
			redirect_to access_denied_path
		end
	end

	def create
		@user = User.find(params[:user_id])
		@role = @user.roles.create(params[:role])
		t = Role.find_by_name(params[:role][:name_select])

		if t
			@role.description = t.description
			@role.permissions = t.permissions
		end

		if @role.save
			redirect_to admin_user_path(@user.id)
		else
			raise @role.errors.first.to_s
		end
	end

	def new
		if puede "Asignar Rol"
			@user = User.find(params[:user_id])
			tmp = Role.select(:name).uniq
			@roles_available = Array.new

			tmp.each do |t|
				@roles_available.push(t.name)
			end
			tmp2 = @user.roles
			current_roles = []
			tmp2.each do |t|
				current_roles.push(t.name)
			end

			@roles_available.push("Nuevo rol")
			@roles_available = @roles_available - current_roles
		else
			redirect_to access_denied_path
		end
	end

	def new_empty
		if puede "Crear Rol"
			@role = Role.new
		else
			redirect_to access_denied_path
		end
	end

	def create_empty
		if params[:cancel]
			redirect_to admin_roles_path
		else
			@role = Role.create(params[:role])
			if @role.save
				redirect_to admin_role_show_path(@role.name)
			else
				render :action => 'new_empty'
			end
		end
	end

	def show
		if puede "Ver Rol"
			perms = Permission.all
			@perms1 = perms.in_groups(2)
			@role = Role.find_by_name(params[:name])
			if @role.nil?
				redirect_to admin_roles_path
			else			
				tmp = @role.permissions.all
				@current_perms = Array.new
				tmp.each do |t|
					@current_perms.push(t.id)
				end
			end
		end
	end

	def destroy
		if puede "Eliminar Rol"
			if params[:user_id].present?
				@user = User.find(params[:user_id])
				@role = @user.roles.find(params[:id])

				if @user.email != "nestor.bermudez@unitec.edu" || testing
					@role.destroy
				end
				redirect_to new_admin_user_role_path(@user.id)
			else
				@roles = Role.where(:name => params[:name])
				@roles.each do |r|
					r.destroy
				end

				redirect_to admin_roles_path
			end
		else
			redirect_to access_denied_path
		end
	end
end

app/views/admin/roles/index.html.erb
<div class="page-title">
    <div class="row">
    	<div class="contact-form span3"></div>        
        <div class=" contact-us contact-form login-form span7">
			<% if @roles.size > 0 %>
				<h3 style="margin-left:40%;">Roles</h3>
				<hr/>
				<table id="hor-minimalist-b">
					<thead>
						<tr>
							<th scope="col">Rol</th>
							<th scope="col">Descripción</th>
							<th scope="col"></th>
							<th scope="col"></th>
						</tr>
					</thead>
					<tbody>
					<% @roles.each do |u| %>
						<tr>
							<td><%= u.name %></td>
							<td><%= u.description %></td>
							<td>
								<% if puede "Modificar Rol" %>
								<%= link_to 'Editar',  admin_roles_update_path(u.name), :method => :post %>
								<% end %>
							</td>
							<td>
								<% if puede "Eliminar Rol" %>
								<%= link_to 'Eliminar',  admin_roles_update_path(u.name), :method => :delete,
							 :data => { :confirm => '¿Seguro que desea eliminar este archivo?' } %>
							 	<% end %>
							</td>
						</tr>
					<% end %>
					</tbody>
				</table>
			<% else %>
				<h2>Aún no ha creado roles.</h2>
			<% end %>
			<br/>
			<br/>
		</div>
	</div>
</div>
<div class="call-to-action-text ">
	<div class="ca-button">
	    <a href="<%= admin_path %>">Atrás</a>
	</div>
	<% if puede "Crear Rol" %>
	<div class="ca-button">
	    <a href="<%= admin_roles_new_path %>">Nuevo rol</a>
	</div>
	<% end %>
</div>

app/views/admin/roles/new.html.erb
<script type="text/javascript">
var var_control = 1, nuevo = 0;
function show_new_role(){ 
	$('div[id="new_role_div"]').each (function() {  this.style['display'] = 'block' });
	$('div[id="asignar_div"]').each (function() {  this.style['display'] = 'none' });
	nuevo = 1;
}
function hide_new_role(){ 
	$('div[id="new_role_div"]').each (function() {  this.style['display'] = 'none' });
	$('div[id="asignar_div"]').each (function() {  this.style['display'] = 'block' });
	nuevo = 0;
}
</script>
<div class="page-title">
	<h1 class="title">&nbsp;&nbsp;&nbsp;<%= @user.name %></h1>
    <div class="row">
    	
    	<div class="contact-us contact-form span"></div>
        <div class="contact-us contact-form login-form span4">
        	<h2>Roles actuales</h2>
            <hr/>
        	<% if @user.roles.any? %>
			<table id="hor-minimalist-c">
				<thead>
					<tr>
						<th scope="col">Rol</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
				<% @user.roles.each do |u| %>
					<tr>
						<td><%= u.name %></td>
						<td>
							<% if puede("Eliminar Rol") || true%>
							<%= link_to (image_tag('file_delete.png', :size =>'15x15')), admin_user_role_path(@user, u), :method => :delete, :data => { :confirm => '¿Esta seguro?' }%>
							<% end %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
			<% else %>
				<p>Aun no tiene roles asignados</p>
			<% end %>
        </div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Asignación de roles</h2>
            <hr/>            
            <%= form_for [:admin, @user, @user.roles.build] do |f| %>
            	<div class="name">
            		<h3>Agregar rol:</h3>
        			<%= f.select :name_select, options_for_select(@roles_available), {},
        			{:onChange => "if(this.value == 'Nuevo rol') show_new_role();else hide_new_role();"}%>
        		</div>
            	<div id="new_role_div" style="display:<%if @roles_available.size == 1 %>block<%else%>none<%end%>">
	              <div class="name">
	                <%= f.label :name, 'Rol*', :class => 'nameLabel' %>
	                <%= f.text_field :name, :placeholder => 'Ingrese nombre del rol...' %>
	              </div>
	              <div class="name">
	                <%= f.label :description, 'Descripción*', :class => 'nameLabel' %>
	                <%= f.text_field :description, :placeholder => 'Descripción del rol...' %>
	              </div>
                  <p>*Dato obligatorio</p><br/>
                  <button type="submit" name="create">Crear</button>                
                  <button type="submit" name="cancel">Cancelar</button>
            	</div>
            	<div id="asignar_div" style="display:<%if @roles_available.size == 1 %>none<%else%>block<%end%>">
					<button type="submit" name="asignar">Asignar</button>
				</div>           	
            	
            <% end %>
        </div>
    </div>
</div>

<div class="call-to-action-text ">
	<div class="ca-button">	
		<%= link_to 'Atrás', admin_user_path(@user.id) %>
	</div>
</div>

app/views/admin/roles/new_empty.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-us contact-form  span3">
        </div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Nuevo rol</h2>
            <hr/>            
            <%= form_for [:admin, @role], :url=>{:action => 'create_empty'} do |f| %>
	              <div class="name">
	                <%= f.label :name, 'Rol*', :class => 'nameLabel' %>
	                <%= f.text_field :name, :placeholder => 'Ingrese nombre del rol...' %>
	              </div>
	              <div class="name">
	                <%= f.label :description, 'Descripción*', :class => 'nameLabel' %>
	                <%= f.text_field :description, :placeholder => 'Descripción del rol...' %>
	              </div>
                  <p>*Dato obligatorio</p><br/>
              	  <button type="submit" name="create">Crear</button>         
                  <button type="submit" name="cancel">Cancelar</button>            	
            <% end %>
        </div>
    </div>
</div>

app/views/admin/roles/show.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-us contact-form  span3">
        </div>
        <div class="contact-form login-form span7">
            <h2>Permisos de <%= @role.name%></h2>
            <hr/>
            <%= form_tag({:action => 'add_permissions', :controller => 'admin/permissions'}) do %>
              <table>
                <tr>
                  <td style="width: 30%">
                    <% @perms1[0].each do |per| %>
                      <% if !per.nil? %>
                        <label class="checkbox">
                          <input type="checkbox" name="role[permissions_list][<%=per.id%>]"
                          <%= 'checked' if (@current_perms.include? per.id)%>><%= per.name %>
                        </label>
                      <% end %>
                    <% end %>
                  </td>
                  <td style="width: 30%; vertical-align: top">
                  <% @perms1[1].each do |per| %>
                      <% if !per.nil? %>
                        <label class="checkbox">
                        <input type="checkbox" name="role[permissions_list][<%=per.id%>]" 
                        <%= 'checked' if (@current_perms.include? per.id)%>><%= per.name %>
                      <% end %>
                    </label>                  
                  <% end %>

                  </td>
                </tr>
              </table>
              <% if puede "Modificar Rol" %>
              <button class="mine" type="submit" name="actualizar" style="margin-left: 30px;">Actualizar</button>
              <% end %>
              <button class="mine" type="submit" name="atras">Atrás</button>
            <% end %>
        </div>
    </div>
</div>