config/routes.rb
Regionsps::Application.routes.draw do

  resources :events, :only => [:index]
  resources :articles, :only => [:index], :path => 'articulos'
  put 'admin/articulos/:id/active', to: 'admin/articles#active', :as => "admin_active_article"
  put 'admin/articulos/:id/publish', to: 'admin/articles#publish', :as => "admin_publish_article"

  resources :sessions, :only => [:new, :create, :destroy]
  get 'forgot_password'           => 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password_request', :as => "reset_password_request"
  get 'reset_password', to: 'sessions#reset_password', :as => "reset_password"
  post 'update_password', to: 'sessions#update_password', :as => "update_password"
  
  match '/recursos'              => 'resources#categories'
  match '/recursos/:id'          => 'resources#index', :as => :recursos_f
  match '/recursos/:c_id/:t_id'  => 'resources#bytag', :as => :recursos_t
  match '/nosotros'              => 'static_pages#about_us'
  match '/admin'                 => 'sessions#admin'
  match '/signin'                => 'sessions#create', :via => :post
  match '/signin'                => 'sessions#admin', :via => :get
  match '/signout'               => 'sessions#destroy'
  match '/calendar'              => 'events#index'
  match '/dashboard'             => 'admin/stadistics#index'
  match '/contact_us'            => 'contacts#new', :via => :get, :as => 'contacts'
  match '/contact_us'            => 'contacts#send_message'
  match '/message_sent'          => 'contacts#sent'
  match '/trips'            => 'events#trips', :via => :get, :as => 'trips'

  namespace :admin do
    resources :stadistics
    resources :articles, :path => 'articulos'
    resources :goals
    resources :resources, :path => 'recursos' do
      resources :tags, :controller => "tags"
    end

    get '/goals/:year/:chapel' => 'goals#sendToStake', as: 'sendToStake'
    match '/goals/:year/:user/:chapel' => 'goals#index', as: 'goals_index'

    match '/dashboard'           => 'stadistics#index'
    match 'recursos/new_tag/:id' => 'resources#new_tag', :as => :new_tag, :via => :post
    match 'recursos/add_tag/:id' => 'resources#add_tag', :as => :add_tag, :via => :post
    
    get '/stadistic/:month/:year/:chapel/:stake/:user'  => 'stadistics#month', :as => :stadistic_m
    
    get '/stadistic/:chapel/:stake/:user/:year' => 'stadistics#lastyears', as: 'lastyears'
    get '/stadistic/export' => 'stadistic#export', as: 'export'

    resources :events
    match 'events/:id/' => 'events#invite', :as => :invite, :via => :post
    match 'events/:event_id/:group_id' => 'events#uninvite', :as => :uninvite, :via => :delete
    

    resources :users, :path => 'usuarios' do
      resources :roles, :except => [:index, :show]
      resources :groups, :path => 'grupos', :only => [:new, :create, :destroy]
    end    
    
    resources :roles, :only => [:index]
    resources :stories, :path => 'historias', :controller => "stories", :except => [:edit, :update]
    
    resources :categories, :path => 'categorias'
    match 'categorias/:id/' => 'categories#add_tag', :as => :add_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#remove_tag', :as => :remove_tag, :via => :delete
    match 'categorias/:category_id/:tag_id' => 'categories#down_tag', :as =>:down_tag, :via => :post
    match 'categorias/:category_id/:tag_id' => 'categories#up_tag', :as =>:up_tag, :via => :put
  end


  #match '/articulos/articulo1' => 'static_pages#articulo1', :as => :articulo1
  #match '/articulos/articulo2' => 'static_pages#articulo2', :as => :articulo2
  #match '/articulos/articulo3' => 'static_pages#articulo3', :as => :articulo3
  #match '/articulos/articulo4' => 'static_pages#articulo4', :as => :articulo4
  # match '/articulos/articulo5' => 'static_pages#articulo5', :as => :articulo5

  match '/admin/roles/new' => 'admin/roles#new_empty', :via => :get
  match '/admin/roles/new' => 'admin/roles#create_empty', :via => :post
  match '/admin/roles/:name' => 'admin/roles#show', :via => [:post, :get], :as => :admin_role_show
  match '/admin/roles/:name' => 'admin/roles#destroy', :via => :delete, :as => '/admin/roles/update'
  match '/admin/roles/:name/permissions' => 'admin/permissions#add_permissions',:via => :post,
   :as => :admin_role_permissions

  root :to => 'home#index'

  match '/access_denied' => 'static_pages#access_denied', :as => :access_denied
  match '/*rest' => 'static_pages#error_page', :as => :error_page



end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password, :password_old
  attr_accessible :email, :first_name, :last_name, :password, 
                  :password_confirmation, :encrypted_password, :password_old,
                  :phone, :chapel_id, :roles, :password_reset_code

  has_and_belongs_to_many :roles, :join_table => "users_roles"
  has_many :permissions, :through => :roles
  has_and_belongs_to_many :groups, :join_table => "users_groups"
  accepts_nested_attributes_for :roles
  accepts_nested_attributes_for :groups
  belongs_to :chapel

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true, 
                    :uniqueness => true,
                    :format => {:with => email_regex}
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :password , :presence     => true, 
                        :confirmation => true,
                        :length       => { :within => 6..40 }
  validates :chapel_id, :presence => true

  before_save :encrypt_password

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
  	user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def make_password_reset_code
    self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
    self.save(:validate => false)
  end
  
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	def index
		if puede "Ver Usuario"
			@users = User.order(:first_name,:last_name)
		else
			redirect_to access_denied_path
		end
	end

	def new
		if puede "Crear Usuario"
			@user = User.new
		else
			redirect_to access_denied_path
		end
	end

	def create
		if params[:cancel]
			redirect_to admin_users_url
		else
			@user = User.new(params[:user])

			if @user.save
				redirect_to admin_users_url, :notice => 'Usuario creado exitosamente.'
			else
				render :action => "new"
			end
		end		
	end

	def show
		if puede "Ver Usuario"
			@user = User.find(params[:id])
		else
			redirect_to access_denied_path
		end
	end

	def destroy
		if puede "Eliminar Usuario"
			@user = User.find(params[:id])
			@user.destroy

			redirect_to admin_users_url
		else
			redirect_to access_denied_path
		end
	end

	def edit
		if puede "Modificar Usuario"
			@user = User.find(params[:id])
		else
			redirect_to access_denied_path
		end
	end

	def update
		@user = User.find(params[:id])
		if params[:cancel]
			redirect_to admin_user_path(@user.id)
			return 
		else			
			if @user.has_password?(params[:user][:password_old])
				if @user.update_attributes(params[:user])
					redirect_to admin_user_path(@user.id)
				else
					render :action => 'edit'
				end
			else
				render :action => 'edit'
			end
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-form span3"></div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Cambio de contraseña</h2>
            <%= form_for [:admin, @user] do |f| %>
                  <div class="name">
                    <%= f.label :password_old, 'Contraseña actual*', :class => 'nameLabel' %>
                    <%= f.password_field :password_old, :placeholder => 'Ingrese su contraseña actual...' %>
                  </div>
                  <div class="name">
                    <%= f.label :password, 'Nueva contraseña*', :class => 'nameLabel' %>
                    <%= f.password_field :password, :placeholder => 'Ingrese su nueva contraseña...' %>
                  </div>
                  <div class="name">
                    <%= f.label :password_confirmation, 'Confirmar nueva contraseña*', :class => 'nameLabel' %>
                    <%= f.password_field :password_confirmation, :placeholder => 'Repita su nueva contraseña...' %>
                  </div>
                <br/>
                <p>*Dato obligatorio</p><br/>
                <button type="submit" name="create">Cambiar</button>
                <button type="submit" name="cancel">Cancelar</button>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="page-title">
    <div class="row">
    	<div class="contact-form span3"></div>        
        <div class=" contact-us contact-form login-form span7">
			<% if @users.any? %>
				<h3 style="margin-left:40%;">Usuarios</h3>
				<hr/>
				<table id="hor-minimalist-b">
					<thead>
						<tr>
							<th scope="col">Nombre</th>
							<th scope="col">Correo</th>
							<th scope="col"></th>
						</tr>
					</thead>
					<tbody>
					<% @users.each do |u| %>
						<tr>
							<td><%= u.first_name + " " + u.last_name %></td>
							<td><%= u.email %></td>
							<td>
								<% if puede "Modificar Usuario" %>
								<%= link_to 'Administrar', admin_user_path(u.id) %>
								<% end %>
							</td>
						</tr>
					<% end %>
					</tbody>
				</table>
			<% else %>
				<h2>No hay usuarios registrados aún.</h2>
			<% end %>
			<br/>
			<br/>
		</div>
	</div>
</div>

<div class="call-to-action-text ">
	<div class="ca-button">
	    <a href="<%= admin_path %>">Atrás</a>
	</div>
	<% if puede "Crear Usuario" %>
	<div class="ca-button">
	    <a href="<%= new_admin_user_path %>">Nuevo usuario</a>
	</div>
	<% end %>
</div>

app/views/admin/users/new.html.erb
<div class="page-title">
    <div class="row">
        <div class="contact-form span3"></div>
        <div class=" contact-us contact-form login-form span7">
            <h2>Registro de nuevo usuario</h2>
            <hr/>
            <%= form_for [:admin, @user] do |f| %>
                  <div class="name">
                    <%= f.label :first_name, 'Nombre*' %>
                    <%= f.text_field :first_name, :placeholder => 'Ingrese su nombre...' %>
                  </div>
                  <div class="name">
                    <%= f.label :last_name, 'Apellido*' %>
                    <%= f.text_field :last_name, :placeholder => 'Ingrese su apellido...' %>
                  </div>
                  <div class="name">
                    <%= f.label :email, 'Correo electrónico*' %>
                    <%= f.text_field :email, :placeholder => 'Ingrese su correo...', :autocomplete => "off" %>
                  </div>
                  <div class="name">
                    <%= f.label :password, 'Contraseña*', :class => 'nameLabel' %>
                    <%= f.password_field :password, :placeholder => 'Ingrese su contraseña...' %>
                  </div>
                  <div class="name">
                    <%= f.label :password_confirmation, 'Confirmar contraseña*', :class => 'nameLabel' %>
                    <%= f.password_field :password_confirmation, :placeholder => 'Repita su contraseña...' %>
                  </div>
                  <div class="name">
                    <%= f.label :phone, 'Teléfono*' %>
                    <%= f.text_field :phone, :placeholder => 'Ingrese su número de teléfono...', :autocomplete => "off" %>
                  </div>
                  <div class="name">
                    <%= f.label :chapel_id, 'Capilla*' %>
                    <%= f.collection_select :chapel_id, Chapel.all, :id, :name %>
                  </div>
                <br/>
                <p>*Dato obligatorio</p><br/>
                <button type="submit" name="create">Registrar</button>
                <button type="submit" name="cancel">Cancelar</button>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="page-title">
    <div class="row">
    	<br/>
    	<div class="contact-form span3"></div>        
        <div class=" contact-us contact-form login-form span7">
        	<br/>
			<h2>
				Información de <%= @user.name %>.
			</h2>
			<hr/>
			<div class="margin-div">
				<h5>
					Correo: <span class="violet"><%= @user.email%></span>
				</h5>
				<% if puede "Ver Telefono" %>
				<h5>
					Teléfono: <span class="violet"><%= @user.phone%></span>
				</h5>
				<% end %>
				<h5>
					Capilla: <span class="violet">
						<% if @user.chapel_id != nil %>
							<%= Chapel.find(@user.chapel_id).name%>
						<% else %>
							No pertenece a alguna capilla en particular
						<% end %>
					</span>
				</h5>				
			</div>
			<hr/>
			<table>
				<tr>
					<% if puede "Ver Rol" %>
					<td style="vertical-align:top;">
						<div class="margin-div-user">
							<h4>Roles</h4>
							<hr/>
							<% if @user.roles.any? %>
							<ul>
								<% @user.roles.each do |role| %>
								<li><%= role.name %></li>
								<% end %>
							</ul>
							<% else %>
								<em>Aun no tiene roles asignados</em><br/>
							<% end %>
						</div>
					</td>
					<% end %>
					<% if puede "Ver Grupo" %>
					<td style="vertical-align:top;">
						<div class="margin-div-user">
							<h4>Grupos</h4>
							<hr/>
							<% if @user.groups.any? %>
							<ul>
								<% @user.groups.each do |group| %>
								<li><%= group.name %></li>
								<% end %>
							</ul>
							<% else %>
								<em>Aun no tiene grupos asignados</em><br/>
							<% end %>
						</div>
					</td>
					<% end %>
				</tr>
			</table>
			
			
			<br/>
			<br/>
		</div>
	</div>
</div>

<div class="call-to-action-text ">
	<div class="ca-button">	
		<% if (puede("Eliminar Usuario")) && (@user.email != "nestor.bermudez@unitec.edu") && (current_user.email != @user.email)%>
		<%= link_to 'Eliminar Usuario', admin_user_path(@user.id), :method => :delete, 
		:data => { :confirm => '¿Seguro que desea eliminar este usuario?' } %>
		<% end %>

		<!-- TODO: agrupar usuarios!-->
		<% if (puede "Asignar Grupo")  || (current_user.roles.where(:name => "Administrador").any?)  %>
		<%= link_to 'Editar grupos', new_admin_user_group_path(@user.id) %>
		<% end %>

		<% if (puede "Asignar Rol") && @user.email != current_user.email%>
	    <%= link_to 'Editar roles', new_admin_user_role_path(@user.id) %>
		<% end %>	

	    <% if current_user.id == @user.id %>
	    <%= link_to 'Cambiar contraseña', edit_admin_user_path(@user.id) %>
		<% end %>

		<a href="<%= admin_users_path %>">Atrás</a>
	</div>
</div>